#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: render-postgres-web
  type: web
  env: static
  buildCommand: cd render-postgres && yarn rw deploy render web
  staticPublishPath: ./render-postgres/web/dist
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: API_DOMAIN
    fromService:
      name: render-postgres-api
      type: web
      property: host
  routes:
  - type: rewrite
    source: /.redwood/functions/*
#####
# NOTE: replace destination api url after first deploy to Render
# example:
#   destination: https://myredwoodproject-api.onrender.com/*
#####
    destination: replace_with_api_url/*
  - type: rewrite
    source: /*
    destination: /index.html
- name: render-postgres-api
  type: web
  env: node
  region: oregon
  buildCommand: cd render-postgres && yarn && yarn rw build api
  startCommand: cd render-postgres && yarn rw deploy render api
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: DATABASE_URL
    fromDatabase:
      name: render-postgres-db
      property: connectionString

databases:
  - name: render-postgres-db
    region: oregon
