# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to `true` to forward the client machine's ssh credentials
#
# See https://redwoodjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "ec2-34-200-219-134.compute-1.amazonaws.com"
username = "ubuntu"
agentForward = true
sides = ["api","web"]
packageManagerCommand = "yarn"
monitorCommand = "pm2"
path = "/var/www/deploy-target-ci/baremetal"
processNames = ["serve"]
repo = "git@github.com:redwoodjs/deploy-target-ci.git"
branch = "main"
keepReleases = 5

# If you have separate api and web servers:
#
# [[production.servers]]
# host = "api.server.com"
# user = "user"
# agentForward = true
# sides = ["api"]
# path = "/var/www/app"
# repo = "git@github.com:redwoodjs/redwood.git"
# branch = "main"
# processNames = ["api"]
#
# [[production.servers]]
# host = "web.server.com"
# user = "user"
# agentForward = true
# sides = ["web"]
# path = "/var/www/app"
# repo = "git@github.com:redwoodjs/redwood.git"
# branch = "main"
# migrate = false # only one server in a cluster needs to migrate
# processNames = ["web"]
