name: Approve Renovate

on:
  # Try enabling auto-merge for all open pull requests. (Only recommended for testing.)
  push:

  # Try enabling auto-merge for all open pull requests.
  # schedule:
  #   - cron: '*/5 * * * *'

  # Try enabling auto-merge for a pull request when a draft is marked as “ready for review”, when
  # a required label is applied or when a “do not merge” label is removed, or when a pull request
  # is updated in any way (opened, synchronized, reopened, edited).
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

  # Try enabling auto-merge for the specified pull request or all open pull requests if none is specified.
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

# this job may trigger other workflows; use personal token because actions don't trigger actions
jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - name: auto-approve-step
        uses: hmarr/auto-approve-action@v2
        if: github.event.pull_request.user.login == 'app/renovate' || github.event.pull_request.user.login == 'renovate[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"   
